### ISSUE TITLE
Upload a release version

### ISSUE THREAD

**Issue by 7wOv6ySCjo** [thetealviper/Spigot_ChatBubbles#2]
Hi, could you please upload a compiled .jar file please, I am finding it difficult to compile this project.

**Comment by thetealviper** [comment]
The compiled .jar will always be on Spigot which is where I intend the hub of the plugin discussion to be (or my discord server). I don't check GitHub so your communication attempts will be missed, much like this one 😂 Go here:
 https://www.spigotmc.org/resources/chatbubbles-1-18-factions-citizens-compatible-placeholderapi.49387/
