### ISSUE TITLE
ChatBubble_See_Own_Bubbles does not work

### ISSUE THREAD

**Issue by nhanledev** [thetealviper/Spigot_ChatBubbles#3]
Hello,

I try to disable viewing own hologram but it does not work.
The hologram is also show on top of vanished player (CMI).

I use DecentHologram as it is recommended by ChatBubbles with default config.

**Comment by thetealviper** [comment]
This is a bug with the most recent versions of DecentHolograms in at the least 1.18 which is the current version the plugin supports. I am unaware of 1.19 behavior, however that is not what the plugin claims to be released for so. If you have this issue with HolographicDisplays as well, then that is possibly an issue on my end and feel free to reach out over my Discord @ https://discord.gg/H32FcPp

**Comment by thetealviper** [comment]
Update from far in the future: This was an issue on both DecentHologram and HolographicDisplay's end. It has since been addressed and fixed by them through a code deprecation/update. ChatBubbles uses the new methods and everything works as of 1.20.
